name: assign_review_by_comment by issue_comment
on: [issue_comment, pull_request_review]

jobs:
  assign_review_by_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"
      - name: assign_review_by_comment
        uses: cats-oss/github-action-auto-assign@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}